name: ownerbat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # ---------------- STATE ----------------
  get: 4.6.6
  get_storage: 2.1.1

  # ---------------- NETWORK (DIO v5) ----------------
  dio: ^5.9.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  http: ^1.1.0

  # ---------------- UI / TEXT ----------------
  google_fonts: 6.2.1
  auto_size_text: 3.0.0
  shimmer: 3.0.0
  cupertino_icons: 1.0.8


  # ---------------- IMAGES & LAYOUT ----------------
  cached_network_image: 3.3.1
  carousel_slider: 5.0.0
  flutter_svg: 2.0.10+1
  flutter_staggered_grid_view: 0.7.0
  image_picker: 1.1.1

  # ---------------- FORMS ----------------
  intl_phone_field: 3.2.0

  # ---------------- WEB ----------------
  webview_flutter: 4.7.0
  flutter_html: 3.0.0-beta.2
  url_launcher: 6.2.6

  # ---------------- FIREBASE ----------------
  firebase_core: 2.29.0
  firebase_auth: 4.19.1
  cloud_firestore: 4.16.1
  firebase_messaging: 14.8.1
  firebase_storage: 11.7.1

  # ---------------- MAPS ----------------
  google_maps_flutter: 2.6.0
  map_launcher: ^4.4.2

  # ---------------- PERMISSIONS ----------------
  permission_handler: ^12.0.1

  #  google_maps_place_picker_mb:
#    git:
#      url: https://github.com/SmarterVision/google_maps_place_picker_mb.git
#      ref: 3.1.3

  # ---------------- UTIL ----------------
  collection: ^1.18.0
#  flutter_google_places_sdk: 0.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.2

  # ---------------- APP ASSETS ----------------
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.4

  # WINDOWS SUPPORT
  win32: 5.5.4

flutter:
  uses-material-design: true

  assets:
    - config/
    - assets/img/
    - assets/icon/
